export type Place = {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  provisional?: boolean;
  summary: string;
  image?: {
    src: string;
    alt: string;
    credit: string;
    sourceUrl: string;
  };
};

export type TripStop = {
  id: string;
  time: string;
  title: string;
  placeId?: string;
  meta: string;
  detail: string;
  transit?: string;
  status?: "예약" | "확인 필요" | "미정" | "장거리";
  history?: string;
  question?: string;
};

export type DayPlan = {
  id: "day1" | "day2" | "day3";
  tab: string;
  date: string;
  weekday: string;
  eyebrow: string;
  theme: string;
  color: string;
  distanceNote: string;
  summary: string;
  alert?: string;
  route: string[];
  stops: TripStop[];
};

export const places: Record<string, Place> = {
  hotel: {
    id: "hotel",
    name: "머큐어 앰배서더 서울 마곡",
    address: "서울 강서구 마곡중앙로 143",
    lat: 37.566148,
    lng: 126.82563,
    summary: "마곡나루역과 서울식물원에 가까운 이번 여행의 숙소입니다. 장거리 이동 뒤 쉬고, 2일차에는 비가 그친 뒤 도심으로 출발하는 거점으로 이용합니다.",
  },
  magokMeal: {
    id: "magokMeal",
    name: "마곡 점심 지역",
    address: "호텔·마곡나루역 인근, 식당 미정",
    lat: 37.5661,
    lng: 126.8262,
    provisional: true,
    summary: "호텔과 마곡나루역 주변에서 식당을 정할 예정인 구역입니다. 가족 좌석, 대기 시간, 아이가 먹기 편한 메뉴를 기준으로 당일 선택하세요.",
  },
  magokNaruFood: {
    id: "magokNaruFood",
    name: "오봉집 · 투썸플레이스 마곡나루역점",
    address: "서울 강서구 마곡중앙5로 6",
    lat: 37.56684,
    lng: 126.82798,
  },
  seoulBotanic: {
    id: "seoulBotanic",
    name: "서울식물원",
    address: "서울 강서구 마곡동로 161",
    lat: 37.56917,
    lng: 126.836014,
  },
  historyMuseum: {
    id: "historyMuseum",
    name: "대한민국역사박물관",
    address: "서울 종로구 세종대로 198",
    lat: 37.573713,
    lng: 126.978338,
    summary: "광화문 앞에서 개항 이후 오늘까지 대한민국의 근현대사를 살펴보는 국립 박물관입니다. 가족과 함께 민주주의, 산업화, 분단과 일상의 변화를 시대순으로 연결해 보기 좋습니다.",
    image: {
      src: "https://commons.wikimedia.org/wiki/Special:FilePath/20240413%20National%20Museum%20of%20Korean%20Contemporary%20History.jpg?width=900",
      alt: "광화문 앞 대한민국역사박물관 건물",
      credit: "Jjw · CC BY 4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:20240413_National_Museum_of_Korean_Contemporary_History.jpg",
    },
  },
  daehangnoMeal: {
    id: "daehangnoMeal",
    name: "대학로·창경궁 저녁 지역",
    address: "창경궁 인근, 식당 미정",
    lat: 37.5817,
    lng: 127.001,
    provisional: true,
    summary: "창경궁 야간 관람 전에 저녁을 먹을 예정인 대학로·창경궁 주변 구역입니다. 관람 입장 시각과 도보 이동을 고려해 가까운 식당을 선택하세요.",
  },
  changgyeonggung: {
    id: "changgyeonggung",
    name: "창경궁",
    address: "서울 종로구 창경궁로 185",
    lat: 37.577678,
    lng: 126.993855,
    summary: "조선 왕실의 생활 공간이었던 궁궐로, 명정전과 통명전, 춘당지까지 이어지는 길에서 궁궐의 쓰임과 일제강점기 훼손 뒤 복원 과정을 함께 살펴볼 수 있습니다.",
    image: {
      src: "https://commons.wikimedia.org/wiki/Special:FilePath/Korea-Seoul-Changgyeonggung-Myeongjeongjeon-01.jpg?width=900",
      alt: "창경궁 명정전과 앞뜰",
      credit: "d'n'c · CC BY-SA",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Korea-Seoul-Changgyeonggung-Myeongjeongjeon-01.jpg",
    },
  },
  anguk: {
    id: "anguk",
    name: "안국역",
    address: "서울 종로구 율곡로 지하 62",
    lat: 37.576477,
    lng: 126.985443,
    summary: "창덕궁과 서울공예박물관, 북촌으로 이어지는 도심 이동 거점입니다. 3호선을 이용하며 출구에 따라 보행 거리가 달라질 수 있습니다.",
  },
  changdeokgung: {
    id: "changdeokgung",
    name: "창덕궁·후원",
    address: "서울 종로구 율곡로 99",
    lat: 37.579032,
    lng: 126.991012,
    summary: "자연 지형을 살린 배치로 잘 알려진 조선의 궁궐입니다. 인정전 일대와 예약제로 운영되는 후원을 함께 보면 왕실의 공식 공간과 휴식 공간의 차이를 이해하기 좋습니다.",
    image: {
      src: "https://commons.wikimedia.org/wiki/Special:FilePath/Changdeokgung0001.jpg?width=900",
      alt: "창덕궁의 전각과 마당",
      credit: "Ori~ · Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Changdeokgung0001.jpg",
    },
  },
  angukMeal: {
    id: "angukMeal",
    name: "안국역 점심 지역",
    address: "안국역 인근, 식당 미정",
    lat: 37.5768,
    lng: 126.9848,
    provisional: true,
    summary: "안국역 주변에서 점심을 고를 예정인 구역입니다. 이후 일정이 실내 관람과 후원 해설로 이어지므로 이동이 짧고 대기가 적은 곳이 적합합니다.",
  },
  craftMuseum: {
    id: "craftMuseum",
    name: "서울공예박물관",
    address: "서울 종로구 율곡로3길 4",
    lat: 37.5767,
    lng: 126.983548,
    summary: "옛 풍문여고 터에 자리한 공예 전문 박물관입니다. 전통 재료와 장인의 기술이 오늘의 생활과 디자인으로 어떻게 이어지는지 실내 전시로 살펴볼 수 있습니다.",
    image: {
      src: "https://commons.wikimedia.org/wiki/Special:FilePath/Seoul%20Museum%20of%20Craft%20Art.jpg?width=900",
      alt: "서울공예박물관 외관",
      credit: "Youngjin · CC BY-SA 4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Seoul_Museum_of_Craft_Art.jpg",
    },
  },
  cheonhaBossam: {
    id: "cheonhaBossam",
    name: "천하보쌈",
    address: "서울 종로구 창덕궁1길 8",
    lat: 37.57986,
    lng: 126.989722,
    summary: "창덕궁 인근 원서동에 자리한 유명 보쌈집입니다. 가족과 늦은 점심으로 보쌈을 먹고 오후 3시 20분경 식사를 마쳤습니다.",
  },
  insadong: {
    id: "insadong",
    name: "인사동 거리",
    address: "서울 종로구 인사동길 일대",
    lat: 37.574242,
    lng: 126.985664,
    summary: "안국역 6번 출구에서 이어지는 인사동 거리입니다. 오랜만에 찾은 가족은 골목과 상점을 구경하고, 하루의 끝에는 다시 돌아와 손수건을 샀습니다.",
  },
  cheonggyecheon: {
    id: "cheonggyecheon",
    name: "청계천",
    address: "서울 종로구 청계천로 광통교·청계광장 일대",
    lat: 37.56901,
    lng: 126.98274,
    summary: "인사동길을 따라 내려오다 만난 도심의 물길입니다. 많은 사람이 물가에 앉아 발을 담그고 쉬었고, 둘째 딸도 함께 시원한 휴식을 즐겼습니다.",
  },
  youngpoongBooks: {
    id: "youngpoongBooks",
    name: "영풍문고 종각종로본점",
    address: "서울 종로구 청계천로 41 영풍빌딩 지하 1·2층",
    lat: 37.56948,
    lng: 126.98232,
    summary: "청계천에서 광화문 쪽으로 걷다가 들른 대형 서점입니다. 가족이 잠시 책과 문구를 구경한 뒤 다시 청계천 산책을 이어 갔습니다.",
  },
  gwanghwamunSquare: {
    id: "gwanghwamunSquare",
    name: "광화문 거리·광장",
    address: "서울 종로구 세종대로 일대",
    lat: 37.57239,
    lng: 126.97691,
    summary: "청계천의 사람들과 거리 음악을 지나 도착한 광화문 거리입니다. 넓게 열린 도심 풍경을 가족과 함께 걸으며 저녁 산책을 마무리했습니다.",
  },
  jongmyo: {
    id: "jongmyo",
    name: "종묘",
    address: "서울 종로구 종로 157",
    lat: 37.571035,
    lng: 126.995147,
    summary: "조선 왕과 왕비의 신주를 모시고 제례를 올리던 왕실 사당입니다. 길게 이어진 정전과 절제된 공간 구성에서 조선 왕실의 유교적 예법을 살펴볼 수 있습니다.",
    image: {
      src: "https://commons.wikimedia.org/wiki/Special:FilePath/Jeongjeon%2C%20Jongmyo%20Shrine%20%28oblique%29%20-%20Seoul%2C%20Korea.jpg?width=900",
      alt: "종묘 정전의 긴 전각",
      credit: "Daderot · Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jeongjeon,_Jongmyo_Shrine_(oblique)_-_Seoul,_Korea.jpg",
    },
  },
  heojunMuseum: {
    id: "heojunMuseum",
    name: "허준박물관",
    address: "서울 강서구 허준로 87",
    lat: 37.568,
    lng: 126.851,
    summary: "강서구와 인연이 깊은 의관 허준의 생애와 《동의보감》을 중심으로 조선 의학을 소개하는 박물관입니다. 사람을 살피고 지식을 책으로 나눈 의미를 가족과 이야기해 보기 좋습니다.",
    image: {
      src: "https://culture.gangseo.seoul.kr/resources/gsfc/img/sub/hj-img_01.jpg",
      alt: "허준박물관 입구와 전경",
      credit: "강서구 허준박물관",
      sourceUrl: "https://culture.gangseo.seoul.kr/gsfc/main/contents.do?menuNo=800119",
    },
  },
  seodaemunPrison: {
    id: "seodaemunPrison",
    name: "서대문형무소역사관",
    address: "서울 서대문구 통일로 251",
    lat: 37.574271,
    lng: 126.956071,
    summary: "일제강점기 독립운동가들이 수감되었던 현장을 보존한 역사관입니다. 옥사와 전시관을 통해 식민지 억압, 독립운동, 민주화운동의 기억을 차분히 살펴봅니다.",
    image: {
      src: "https://commons.wikimedia.org/wiki/Special:FilePath/Seodaemun%20Prison%2020190331%20162931.jpg?width=900",
      alt: "붉은 벽돌로 지어진 서대문형무소역사관",
      credit: "H. Y. Shin 000 · CC0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Seodaemun_Prison_20190331_162931.jpg",
    },
  },
  warMemorial: {
    id: "warMemorial",
    name: "전쟁기념관",
    address: "서울 용산구 이태원로 29",
    lat: 37.53653,
    lng: 126.977139,
    summary: "한반도의 전쟁사와 6·25전쟁, 국군의 역사를 전시하는 기념관입니다. 전쟁의 과정뿐 아니라 희생과 평화의 의미에 초점을 두고 핵심 전시를 골라 관람합니다.",
    image: {
      src: "https://commons.wikimedia.org/wiki/Special:FilePath/War%20Memorial%20Korea%2020150623%2018%20%2819044457186%29.jpg?width=900",
      alt: "서울 용산 전쟁기념관 전경",
      credit: "Jeon Han / Korea.net · CC BY-SA",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:War_Memorial_Korea_20150623_18_(19044457186).jpg",
    },
  },
  yongsanMeal: {
    id: "yongsanMeal",
    name: "삼각지·용산 저녁 지역",
    address: "전쟁기념관 인근, 식당 미정",
    lat: 37.5354,
    lng: 126.9739,
    provisional: true,
    summary: "전쟁기념관 관람 뒤 저녁과 휴식을 위해 잡은 삼각지·용산 주변 구역입니다. 전주로 출발하기 전 주차, 화장실, 운전자 휴식 시간을 함께 확보하세요.",
  },
};

export const dayPlans: DayPlan[] = [
  {
    id: "day1",
    tab: "1일차",
    date: "8.12",
    weekday: "수",
    eyebrow: "서울 도착 · 마곡에서 보낸 첫날",
    theme: "일찍 열린 객실과 시원한 식물원에서 여행의 숨을 고르다",
    color: "#c2410c",
    distanceNote: "전주 → 마곡 · 오후 2시경 도착",
    summary: "오봉집 · 투썸 · 서울식물원 · 호텔 수영",
    route: ["hotel", "magokNaruFood", "seoulBotanic", "hotel"],
    stops: [
      {
        id: "d1-hotel",
        time: "14:00경",
        title: "머큐어 서울 마곡 도착",
        placeId: "hotel",
        meta: "자가용 · 지하 4층 주차",
        detail: "서울 숙소에 도착해 지하 4층에 차를 세우고 체크인을 위해 프런트로 올라갔습니다.",
        transit: "자가용",
      },
      {
        id: "d1-checkin",
        time: "14:10–14:30경",
        title: "조기 체크인 · 짐 풀기",
        placeId: "hotel",
        meta: "오후 3시 전 입실 · 평일의 반가운 배려",
        detail: "체크인 시간 전이었지만 가족이 바로 입실할 수 있도록 배려받았습니다. 객실에 짐을 풀고 늦은 점심을 검색했습니다.",
      },
      {
        id: "d1-lunch",
        time: "14:40–15:40경",
        title: "오봉집에서 늦은 점심",
        placeId: "magokNaruFood",
        meta: "낙지볶음 2인분 · 보쌈 2인분",
        detail: "오봉밥을 먹으러 가던 길에 오봉집을 발견해 들어갔습니다. 가족이 함께 낙지볶음과 보쌈을 각각 2인분씩 주문해 든든하게 먹었습니다.",
        transit: "도보",
      },
      {
        id: "d1-cafe",
        time: "15:40–16:20경",
        title: "투썸에서 커피와 다음 장소 찾기",
        placeId: "magokNaruFood",
        meta: "커피 휴식 · 인근 가볼 만한 곳 검색",
        detail: "식사를 마치고 투썸플레이스에서 커피를 마셨습니다. 쉬면서 주변을 검색하다 가까운 서울식물원을 발견했습니다.",
      },
      {
        id: "d1-botanic-walk",
        time: "16:20–16:40경",
        title: "서울식물원으로 걷기",
        placeId: "seoulBotanic",
        meta: "가까운 거리 · 뜨거운 햇볕과 한여름 더위",
        detail: "멀지 않은 거리였지만 햇볕이 강해 걷는 길이 무척 덥게 느껴졌습니다. 천천히 이동하며 그늘과 물을 챙겼습니다.",
        transit: "도보",
      },
      {
        id: "d1-botanic",
        time: "16:40–18:00경",
        title: "서울식물원 관람 · 시원한 휴식",
        placeId: "seoulBotanic",
        meta: "실내 관람 · 더위를 식힌 가족 휴식",
        detail: "식물원에 들어서자 오아시스를 만난 듯 몸과 마음이 시원해졌습니다. 잠시 쉬어 간 뒤 내부의 다양한 식물을 천천히 둘러봤습니다.",
        question: "무더운 도심에서 식물과 녹지가 가족에게 어떤 쉼을 주었을까?",
      },
      {
        id: "d1-mugunghwa",
        time: "18:00–18:40경",
        title: "야외 무궁화 감상 · 호텔 복귀",
        placeId: "seoulBotanic",
        meta: "서울식물원 야외 전시 · 도보 귀환",
        detail: "식물원 야외에 설치된 무궁화 꽃을 함께 바라본 뒤, 지나온 길을 되돌아 숙소로 돌아왔습니다.",
        transit: "도보",
      },
      {
        id: "d1-dinner",
        time: "19:00경",
        title: "객실에서 라면으로 간단한 저녁",
        placeId: "hotel",
        meta: "많이 걷고 난 뒤 편하게 쉬는 시간",
        detail: "숙소로 돌아온 뒤 저녁은 라면으로 간단히 해결하고 각자 편안하게 휴식을 취했습니다.",
      },
      {
        id: "d1-pool",
        time: "20:00–21:00경",
        title: "딸과 호텔 수영장",
        placeId: "hotel",
        meta: "첫날의 마지막 가족 시간",
        detail: "저녁 식사 뒤 딸과 함께 수영장에 다녀오며 여행 첫날을 즐겁게 마무리했습니다.",
      },
      {
        id: "d1-sleep",
        time: "22:00경",
        title: "숙면 · 첫날 마무리",
        placeId: "hotel",
        meta: "객실 휴식",
        detail: "장거리 이동과 한여름 산책의 피로를 풀며 깊이 잠들었습니다.",
      },
    ],
  },
  {
    id: "day2",
    tab: "2일차",
    date: "8.13",
    weekday: "목",
    eyebrow: "천하보쌈 · 창덕궁 · 인사동 · 청계천",
    theme: "창덕궁 해설에서 청계천 물가와 광화문 밤거리까지",
    color: "#0369a1",
    distanceNote: "마곡 → 창덕궁 → 인사동 → 청계천·광화문 → 마곡",
    summary: "호텔 조식 · 천하보쌈 · 창덕궁 · 인사동 · 청계천",
    alert: "둘째 딸과 청계천에 발 담그기 · 인사동에서 손수건 구입",
    route: [
      "hotel",
      "cheonhaBossam",
      "changdeokgung",
      "insadong",
      "cheonggyecheon",
      "youngpoongBooks",
      "gwanghwamunSquare",
      "insadong",
      "hotel",
    ],
    stops: [
      {
        id: "d2-breakfast",
        time: "아침 일찍",
        title: "모아시스에서 호텔 조식",
        placeId: "hotel",
        meta: "6층 뷔페 · 빵 · 밥 · 우유",
        detail: "아침 일찍 호텔 6층 모아시스에서 가족과 조식을 먹었습니다. 빵과 밥, 우유 등 여러 음식을 골라 먹었지만 얼음이 모두 떨어져 커피는 마시지 못했습니다.",
      },
      {
        id: "d2-morning-ready",
        time: "조식 후",
        title: "객실 휴식 · 서울 구경 준비",
        placeId: "hotel",
        meta: "서두르지 않고 조금 늦게 출발",
        detail: "조식을 마친 뒤 객실에서 잠시 쉬고 외출 준비를 했습니다. 아침 일정에 여유를 두고 서울 구경을 위해 조금 늦게 숙소를 나섰습니다.",
      },
      {
        id: "d2-depart",
        time: "점심 무렵",
        title: "창덕궁 일대로 이동",
        placeId: "cheonhaBossam",
        meta: "공항철도 → 홍대입구 환승 → 안국·창덕궁",
        detail: "점심시간이 되었지만 바로 식사하지 않고 창덕궁 일대를 향했습니다. 공항철도를 타고 홍대입구에서 전철을 갈아타 서울 도심으로 이동했습니다.",
        transit: "지하철",
      },
      {
        id: "d2-lunch",
        time: "점심 무렵–15:20경",
        title: "천하보쌈에서 늦은 점심",
        placeId: "cheonhaBossam",
        meta: "원서동의 유명 보쌈집 · 보쌈 주문",
        detail: "창덕궁 인근의 유명한 천하보쌈으로 이동해 늦은 점심으로 보쌈을 주문해 먹었습니다. 가족과 여유 있게 식사하고 나온 시간은 오후 3시 20분경이었습니다.",
        transit: "도보·대중교통",
      },
      {
        id: "d2-garden-wait",
        time: "15:20–16:00경",
        title: "창덕궁으로 이동 · 해설 준비",
        placeId: "changdeokgung",
        meta: "천하보쌈 → 창덕궁 · 가까운 도보 이동",
        detail: "오후 3시 20분경 식사를 마친 뒤 창덕궁으로 걸어가 안내 해설을 기다렸습니다.",
      },
      {
        id: "d2-garden",
        time: "16:00–17:00경",
        title: "창덕궁 해설 관람 · 약 1시간",
        placeId: "changdeokgung",
        meta: "안내 해설 · 약 1시간 도보 관람",
        detail: "안내자의 설명을 들으며 약 한 시간 동안 창덕궁 안을 걸었습니다. 궁궐의 공간과 역사 이야기를 가족과 함께 들으며 천천히 둘러보았습니다.",
        history: "자연 지형을 거스르지 않고 정자와 연못을 배치한 조선 궁궐의 공간 감각을 살펴봅니다.",
        question: "자연을 바꾸는 정원과 자연에 맞추는 정원은 어떤 차이가 있을까?",
      },
      {
        id: "d2-daiso",
        time: "창덕궁 관람 후",
        title: "다이소에서 잠깐 구경",
        placeId: "insadong",
        meta: "창덕궁 → 안국역·인사동 입구",
        detail: "창덕궁을 나온 뒤 인사동으로 향하는 길에 다이소에 들러 잠깐 매장을 구경했습니다.",
        transit: "도보",
      },
      {
        id: "d2-insadong-first",
        time: "늦은 오후",
        title: "안국역 6번 출구에서 인사동 산책",
        placeId: "insadong",
        meta: "오랜만에 찾은 인사동 · 뜻밖의 길 발견",
        detail: "오랜만에 인사동을 찾았습니다. 안국역 6번 출구로 나오면 바로 인사동 거리가 시작된다는 것을 이번에 처음 알고, 거리의 상점과 풍경을 보며 천천히 걸었습니다.",
      },
      {
        id: "d2-cheonggye-rest",
        time: "인사동 산책 후",
        title: "청계천에서 둘째 딸과 발 담그기",
        placeId: "cheonggyecheon",
        meta: "인사동길 남쪽 → 청계천 · 물가 휴식",
        detail: "인사동 거리를 따라 쭉 내려오니 청계천 물길과 맞닥뜨렸습니다. 많은 사람이 물가에 앉아 다리에 발을 담그며 쉬고 있었고, 둘째 딸도 함께 청계천에 발을 담그며 시원하게 휴식했습니다.",
        transit: "도보",
      },
      {
        id: "d2-youngpoong",
        time: "청계천 휴식 후",
        title: "영풍문고 구경",
        placeId: "youngpoongBooks",
        meta: "광화문 방향으로 걷다 발견한 서점",
        detail: "광화문 쪽으로 걷다가 영풍문고를 발견해 안으로 들어갔습니다. 가족과 책과 문구를 잠시 둘러본 뒤 다시 청계천으로 향했습니다.",
        transit: "도보",
      },
      {
        id: "d2-cheonggye-music",
        time: "해질 무렵",
        title: "다시 만난 청계천의 사람들과 거리 음악",
        placeId: "cheonggyecheon",
        meta: "사람들이 모인 청계천 명소 · 거리 공연",
        detail: "청계천을 따라 다시 걷자 사람들이 많이 모인 장소가 눈에 들어왔습니다. 물에 발을 담근 사람들 곁으로 길거리 음악이 흐르는 활기찬 풍경을 잠시 함께 즐겼습니다.",
      },
      {
        id: "d2-gwanghwamun",
        time: "저녁",
        title: "광화문 거리 산책",
        placeId: "gwanghwamunSquare",
        meta: "청계천 → 광화문 · 도심 저녁 산책",
        detail: "청계천의 활기찬 풍경을 뒤로하고 광화문에 도착했습니다. 가족과 광화문 거리를 천천히 걸으며 서울 도심의 저녁을 둘러보았습니다.",
        transit: "도보",
      },
      {
        id: "d2-handkerchief",
        time: "숙소 복귀 전",
        title: "인사동으로 돌아와 손수건 구입",
        placeId: "insadong",
        meta: "광화문 → 인사동 · 여행 기념 쇼핑",
        detail: "광화문 산책을 마친 뒤 다시 인사동으로 돌아왔습니다. 거리의 상점에서 손수건을 사며 이날의 도보 여행을 마무리했습니다.",
        transit: "도보",
      },
      {
        id: "d2-return",
        time: "하루 마무리",
        title: "전철을 타고 호텔로 복귀",
        placeId: "hotel",
        meta: "인사동 인근역 → 마곡 숙소",
        detail: "손수건을 산 뒤 가까운 역에서 전철을 타고 머큐어 서울 마곡으로 돌아와 8월 13일 일정을 마쳤습니다.",
        transit: "지하철",
      },
    ],
  },
  {
    id: "day3",
    tab: "3일차",
    date: "8.14",
    weekday: "금",
    eyebrow: "지식 · 독립 · 전쟁과 평화",
    theme: "사람을 살린 지식에서 자유와 평화의 기억까지",
    color: "#047857",
    distanceNote: "강서구 → 서대문 → 용산 → 전주",
    summary: "역사관 3곳 · 20:00 서울 출발",
    alert: "20:00 전주로 출발 · 휴게소 1~2회 이용 시 자정 전후 도착 예상",
    route: [
      "hotel",
      "heojunMuseum",
      "seodaemunPrison",
      "warMemorial",
      "yongsanMeal",
    ],
    stops: [
      {
        id: "d3-breakfast",
        time: "07:30–08:30",
        title: "아침 식사 · 체크아웃 준비",
        placeId: "hotel",
        meta: "짐은 차량에 싣고 바로 이동",
        detail: "두 박물관을 거쳐 바로 전주로 출발할 수 있도록 체크아웃을 마칩니다.",
      },
      {
        id: "d3-depart",
        time: "09:20",
        title: "호텔 출발",
        meta: "허준박물관까지 짧은 택시",
        detail: "무더위와 짐을 고려해 강서구 안에서도 택시 이동을 권장합니다.",
        transit: "택시",
      },
      {
        id: "d3-museum",
        time: "10:00–11:15",
        title: "허준박물관",
        placeId: "heojunMuseum",
        meta: "성인 1,000원 · 학생 500원",
        detail: "허준의 생애, 동의보감과 조선 의학의 체계화를 살펴봅니다.",
        history: "의학 지식을 개인의 비법이 아니라 책으로 정리해 널리 보급한 의미를 생각합니다.",
        question: "지식을 많은 사람이 활용할 수 있게 하는 일은 사회를 어떻게 바꿀까?",
      },
      {
        id: "d3-return",
        time: "11:20–13:20",
        title: "서대문 이동 · 점심",
        placeId: "seodaemunPrison",
        meta: "차량 이동 후 서대문역 인근 식사",
        detail: "짐을 실은 차량으로 서대문까지 이동하고 냉방되는 식당에서 점심을 먹습니다.",
        transit: "자가용",
      },
      {
        id: "d3-prison",
        time: "13:30–15:20",
        title: "서대문형무소역사관",
        placeId: "seodaemunPrison",
        meta: "독립운동 · 민주화운동 · 옥사와 전시관",
        detail: "실내 전시를 중심으로 보고 야외 공간은 햇볕과 체력에 따라 줄입니다.",
        history: "식민지 억압과 독립운동, 이후 민주화운동의 기억이 한 장소에 어떻게 쌓였는지 살펴봅니다.",
        question: "자유를 지키기 위해 감수한 희생을 오늘의 우리는 어떻게 기억해야 할까?",
      },
      {
        id: "d3-war-transit",
        time: "15:20–16:00",
        title: "용산으로 이동",
        placeId: "warMemorial",
        meta: "서대문 → 전쟁기념관 · 차량 이동",
        detail: "17시 입장 마감 전에 도착할 수 있도록 서대문형무소 관람을 15시 20분에 마칩니다.",
        transit: "자가용",
      },
      {
        id: "d3-war",
        time: "16:00–17:50",
        title: "전쟁기념관",
        placeId: "warMemorial",
        meta: "무료 · 실내 · 입장 마감 17:00",
        detail: "호국추모실과 6·25전쟁실을 중심으로 관람하고 야외 전시는 체력에 따라 줄입니다.",
        history: "전쟁을 승패의 기록에만 머물지 않고 사람의 희생과 평화의 가치로 바라봅니다.",
        question: "전쟁을 기억하는 일은 다음 전쟁을 막는 데 어떤 도움을 줄 수 있을까?",
      },
      {
        id: "d3-dinner",
        time: "18:00–19:15",
        title: "삼각지 · 용산 이른 저녁",
        placeId: "yongsanMeal",
        meta: "밤 운전 전 충분히 식사하고 휴식",
        detail: "대기가 짧고 주차가 가능한 식당을 선택해 운전자도 여유 있게 쉽니다.",
        status: "미정",
      },
      {
        id: "d3-drive-prep",
        time: "19:15–20:00",
        title: "출발 준비 · 운전자 휴식",
        placeId: "yongsanMeal",
        meta: "주유 · 화장실 · 생수와 간식 준비",
        detail: "차량 상태와 실시간 교통을 확인하고 운전자는 출발 전 충분히 쉽니다.",
        status: "확인 필요",
      },
      {
        id: "d3-jeonju",
        time: "20:00",
        title: "전주로 출발",
        meta: "약 213km · 휴게소 1~2회 · 자정 전후 도착 예상",
        detail: "졸음이나 피로가 느껴지면 도착 시각보다 안전을 우선해 휴게소에서 쉬고, 필요하면 숙박 후 이동합니다.",
        transit: "자가용",
        status: "장거리",
      },
    ],
  },
];
